# Generated by Django 4.2.7 on 2024-01-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_login_id', models.CharField(max_length=255)),
                ('client_password', models.CharField(max_length=255)),
                ('client_confirm_password', models.CharField(max_length=255)),
                ('client_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_number', models.CharField(max_length=15)),
                ('client_DOB', models.DateField()),
                ('client_address1', models.CharField(max_length=255)),
                ('client_address2', models.CharField(max_length=255)),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(max_length=100)),
                ('client_country', models.CharField(max_length=100)),
                ('client_picture', models.ImageField(blank=True, upload_to='uimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewPropertyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Independent Floor', 'Independent Floor'), ('Builder Floor', 'Builder Floor'), ('Villa', 'Villa')], max_length=20)),
                ('status_name', models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Resale', 'Resale'), ('Under Construction', 'Under Construction')], max_length=20)),
                ('property_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property_size', models.CharField(max_length=200)),
                ('seller_contact_details', models.BigIntegerField()),
                ('email_property', models.TextField(default='Default Amenities')),
                ('property_amenities', models.TextField(default='Default Amenities')),
                ('property_specifications', models.TextField(default='Default Amenities')),
                ('property_total_rooms', models.PositiveIntegerField()),
                ('property_balcony', models.CharField(max_length=200)),
                ('property_total_bathrooms', models.PositiveIntegerField()),
                ('property_address', models.TextField(default='Default Amenities')),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('property_description', models.TextField()),
            ],
        ),
    ]
