# Generated by Django 4.2.7 on 2024-01-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertysaleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_status_name', models.CharField(max_length=100)),
                ('add_status_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewPropertyTypeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_type_name', models.CharField(max_length=100)),
                ('add_type_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='newpropertydata',
            name='property_image',
            field=models.ImageField(upload_to='static/new_property_images/'),
        ),
    ]
