# Generated by Django 4.2.7 on 2024-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertysaleapp', '0004_alter_newpropertydata_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpropertytypedata',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newstatusdata',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='client_picture',
            field=models.ImageField(blank=True, upload_to='static/new_property_images/'),
        ),
    ]
