# Generated by Django 4.2.7 on 2024-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertysaleapp', '0005_newpropertytypedata_seller_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpropertydata',
            name='property_amenities',
            field=models.TextField(default='Default Amenities', null=True),
        ),
    ]
